name: Racebane
options:
  bundleIdPrefix: dk.laura
  deploymentTarget:
    iOS: "16.0"
  developmentLanguage: da
  xcodeVersion: "15.0"

targets:
  Racebane:
    type: application
    platform: iOS
    sources:
      - path: Racebane
    info:
      path: Racebane/Info.plist
      properties:
        CFBundleDisplayName: Racebane
        UIApplicationSupportsIndirectInputEvents: YES
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: NO
          UISceneConfigurations: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        "UISupportedInterfaceOrientations~ipad":
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSLocalNetworkUsageDescription: Racebane bruger lokalt netværk til multiplayer
        NSBonjourServices:
          - _racebane._tcp
        NSCameraUsageDescription: Racebane bruger kameraet til AR-mode
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dk.egernet.laura.Racebane
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: 1
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1,2"
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

  RacebaneTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: RacebaneTests
    dependencies:
      - target: Racebane
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dk.laura.RacebaneTests
        SWIFT_VERSION: "5.0"
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGN_STYLE: Automatic
